<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.1.0 ./character.glb --transform --types
-->

<script lang="ts">
  import type * as THREE from 'three';
  import { Group } from 'three';

  import { T, type Props } from '@threlte/core';
  import { Outlines, useDraco, useGltf, useGltfAnimations } from '@threlte/extras';
  import type { Snippet } from 'svelte';

  let {
    fallback,
    error,
    outlineOpacity = 0.0,
    children,
    ref = $bindable(),
    actions = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
    outlineOpacity?: number
    actions?: any
    mixer?: any
  } = $props()

  ref = new Group()

  type ActionName = 'Wave'
  type GLTFResult = {
    nodes: {
      Hair: THREE.Mesh
      RightLeg: THREE.Mesh
      LeftArm: THREE.Mesh
    }
    materials: {
      ['Handle1Mtl.001']: THREE.MeshStandardMaterial
      ['Rig1Mtl.001']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/character.glb', { dracoLoader: useDraco() })

  const anims = useGltfAnimations<ActionName>(
    () => $gltf,
    () => ref
  )

  $effect(() => {
    actions = anims.actions
  })
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Mesh
        name="Hair"
        receiveShadow
        geometry={gltf.nodes.Hair.geometry}
        material={gltf.materials['Handle1Mtl.001']}
        rotation={[Math.PI / 2, 0, 0]}
      >
      </T.Mesh>
      <T.Mesh
        name="RightLeg"
        receiveShadow
        geometry={gltf.nodes.RightLeg.geometry}
        material={gltf.materials['Rig1Mtl.001']}
        rotation={[Math.PI / 2, 0, 0]}
      >
      </T.Mesh>
      <T.Mesh
        name="LeftArm"
        receiveShadow
        geometry={gltf.nodes.LeftArm.geometry}
        material={gltf.materials['Rig1Mtl.001']}
      >
        <Outlines 
          color="#FFFFFF"
          thickness={0.03}
          screenspace={false}
          transparent={true}
          opacity={outlineOpacity}
        />
      </T.Mesh>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>